@startuml

title __CORE VIEW RESPONDERVAGA's Class Diagram__\n

  namespace com.soundlab.dockerizedjavaapi {
    namespace core.view.respondervaga {
          interface com.soundlab.dockerizedjavaapi.core.view.respondervaga.ResponderVagaViewRequestEmpresa {
              {abstract} + getName()
          }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core.view.respondervaga {
          class com.soundlab.dockerizedjavaapi.core.view.respondervaga.ResponderVagaViewRequestResposta {
              - candidatoId : Long
              - curriculoUrl : String
              - respostasCriterios : List<RespostaCriterio>
              - textContent : String
              - vagaId : Long
              + ResponderVagaViewRequestResposta()
              + equals()
              + getCandidatoId()
              + getCurriculoUrl()
              + getRespostasCriterios()
              + getTextContent()
              + getVagaId()
              + hashCode()
              + setCandidatoId()
              + setCurriculoUrl()
              + setRespostasCriterios()
              + setTextContent()
              + setVagaId()
              + toString()
              # canEqual()
          }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core.view.respondervaga {
          interface com.soundlab.dockerizedjavaapi.core.view.respondervaga.ResponderVagaViewResponseContent {
              {abstract} + getCity()
              {abstract} + getExpirationDate()
              {abstract} + getId()
              {abstract} + getLongDescription()
              {abstract} + getOwner()
              {abstract} + getShortDescription()
              {abstract} + getState()
              {abstract} + getTimeSpan()
              {abstract} + getType()
              {abstract} + getVagaCriterios()
          }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
