// GET ADMINS
GET {{BASE_URL}}users/admins
Content-Type: application/json

> {%
    client.test("Get All Admins", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

// GET CANDIDATOS
GET {{BASE_URL}}users/candidatos
Content-Type: application/json

> {%
    client.test("Get All Candidatos", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

// GET CANDIDATOS BY ID
GET {{BASE_URL}}users/candidatos/2
Content-Type: application/json

> {%
    client.test("Get All Candidatos", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

// GET EMPRESAS
GET {{BASE_URL}}users/empresas
Content-Type: application/json

> {%
    client.test("Get All Empresas", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

// GET EMPRESAS BY ID
GET {{BASE_URL}}users/empresas/6
Content-Type: application/json

> {%
    client.test("Get Empresa By Id", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

// GET VAGAS
GET {{BASE_URL}}vagas
Content-Type: application/json

> {%
    client.test("Get All Vagas", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

// GET VAGA BY ID
GET {{BASE_URL}}vagas/1
Content-Type: application/json

> {%
    client.test("Get Vaga By Id", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

// GET RESPOSTA By ID
GET {{BASE_URL}}respostas/1
Content-Type: application/json

> {%
    client.test("Get Resposta By Id", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###