// GET RANKING By ID
GET {{BASE_URL}}ranking/1
Content-Type: application/json

> {%
    client.test("Get Ranking By Id", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

// GET RESPOSTA By ID
GET {{BASE_URL}}ranking/resposta/1
Content-Type: application/json

> {%
    client.test("Get Resposta By Id", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###