@startuml

title __CORE VIEW HOME's Class Diagram__\n

  namespace com.soundlab.dockerizedjavaapi {
    namespace core.view.home {
          class com.soundlab.dockerizedjavaapi.core.view.home.HomeViewRequestSearch {
              - content : String
              + HomeViewRequestSearch()
              + equals()
              + getContent()
              + getType()
              + hashCode()
              + setContent()
              + setType()
              + toString()
              # canEqual()
          }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core.view.home {
          class com.soundlab.dockerizedjavaapi.core.view.home.HomeViewResponseContent {
              - messages : String
              - vagasBusca : List<ViewResponseVagaLight>
              - vagasUsuario : List<HomeViewResponseVaga>
              + HomeViewResponseContent()
              + equals()
              + getMessages()
              + getVagasBusca()
              + getVagasUsuario()
              + hashCode()
              + setMessages()
              + setVagasBusca()
              + setVagasUsuario()
              + toString()
              # canEqual()
          }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core.view.home {
          interface com.soundlab.dockerizedjavaapi.core.view.home.HomeViewResponseVaga {
              {abstract} + getCity()
              {abstract} + getExpirationDate()
              {abstract} + getId()
              {abstract} + getLongDescription()
              {abstract} + getShortDescription()
              {abstract} + getState()
          }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core.view.home {
          enum SearchType {
            ALL
            ANY
            NONE
            description
            id
          }
    }
  }
  

  com.soundlab.dockerizedjavaapi.core.view.home.HomeViewRequestSearch o-- com.soundlab.dockerizedjavaapi.core.view.home.SearchType : type


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
