@startuml

title __CORE VIEW PUBLISHVAGA's Class Diagram__\n

  namespace com.soundlab.dockerizedjavaapi {
    namespace core {
      namespace view {
        namespace publishvaga {
          class com.soundlab.dockerizedjavaapi.core.view.publishvaga.PublishVagaViewRequestVaga {
              - city : String
              - expirationDate : LocalDateTime
              - longDescription : String
              - ownerId : Long
              - shortDescription : String
              - state : String
              - timeSpan : String
              - vagaCriterios : List<VagaCriterio>
              + PublishVagaViewRequestVaga()
              + equals()
              + getCity()
              + getExpirationDate()
              + getLongDescription()
              + getOwnerId()
              + getShortDescription()
              + getState()
              + getTimeSpan()
              + getType()
              + getVagaCriterios()
              + hashCode()
              + setCity()
              + setExpirationDate()
              + setLongDescription()
              + setOwnerId()
              + setShortDescription()
              + setState()
              + setTimeSpan()
              + setType()
              + setVagaCriterios()
              + toString()
              # canEqual()
          }
        }
      }
    }
  }
  

  com.soundlab.dockerizedjavaapi.core.view.publishvaga.PublishVagaViewRequestVaga o-- com.soundlab.dockerizedjavaapi.core.domain.vaga.VagaType : type


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
