@startuml

title __RANKING's Class Diagram__\n

  namespace com.soundlab.dockerizedjavaapi {
    namespace core {
      namespace view {
        namespace ranking {
          interface com.soundlab.dockerizedjavaapi.core.view.ranking.RankingViewResponseCandidato {
              {abstract} + getAddress()
              {abstract} + getEmail()
              {abstract} + getName()
              {abstract} + getPhoneNumber()
          }
        }
      }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core {
      namespace view {
        namespace ranking {
          interface com.soundlab.dockerizedjavaapi.core.view.ranking.RankingViewResponseContent {
              {abstract} + getCity()
              {abstract} + getExpirationDate()
              {abstract} + getPerfil()
              {abstract} + getRespostas()
              {abstract} + getShortDescription()
              {abstract} + getState()
              {abstract} + getType()
          }
        }
      }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core {
      namespace view {
        namespace ranking {
          interface com.soundlab.dockerizedjavaapi.core.view.ranking.RankingViewResponseResposta {
              {abstract} + getCandidato()
              {abstract} + getCurriculoUrl()
              {abstract} + getPerfilResposta()
              {abstract} + getRespostasCriterios()
              {abstract} + getTextContent()
          }
        }
      }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core {
      namespace view {
        namespace ranking {
          interface com.soundlab.dockerizedjavaapi.core.view.ranking.RankingViewResponseRespostaCriterio {
              {abstract} + getLevel()
              {abstract} + getVagaCriterio()
          }
        }
      }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core {
      namespace view {
        namespace ranking {
          interface com.soundlab.dockerizedjavaapi.core.view.ranking.RankingViewResponseRespostaLight {
              {abstract} + getCandidato()
              {abstract} + getId()
              {abstract} + getPerfilResposta()
          }
        }
      }
    }
  }
  

  namespace com.soundlab.dockerizedjavaapi {
    namespace core {
      namespace view {
        namespace ranking {
          interface com.soundlab.dockerizedjavaapi.core.view.ranking.RankingViewResponseVagaCriterio {
              {abstract} + getName()
              {abstract} + getPmd()
              {abstract} + getWeight()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
